### ISSUE TITLE
[vizbuilder] text wrap data source in measure selector

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#266]
The measure names wrap nicely, but the sources do not:

<img width="290" alt="screen shot 2018-11-02 at 12 18 18 pm" src="https://user-images.githubusercontent.com/1847581/47927355-7212d700-de99-11e8-99ba-e5c6a2aab929.png">

**Comment by frabarz** [comment]
The solution comes in the next PR, but please remove 
```css
.vizbuilder .area-sidebar .select-option .select-value {
 width:auto;
}
```
It interferes with the behavior of flexbox.
