### ISSUE TITLE
[CMS] dialog modals need to respect project nav-height

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#345]
I had to add this to CDC:

```css
.cms {
  & .pt-dialog {
    margin-top: calc(var(--nav-height) + 1rem) !important;
    max-height: calc(100vh - var(--nav-height) - 2rem) !important;
  }
}
```
