### ISSUE TITLE
[CMS] remove text-transform from API input boxes

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#347]
Capitalization matters in API URLs, I had to put this in:

```css
.cms {
  & .pt-input {
    text-transform: none;
  }
}
```

Seems to be inheriting `uppercase` from somewhere else? I noticed this in the simple visualization builder.
