### ISSUE TITLE
[core] switch from normalize.css to James' custom reset

### ISSUE THREAD

**Issue by davelandry** [Datawheel/canon#76]
```css
/* -----------------------------
custom reset
----------------------------- */

/* reset margin & padding */
* {
  margin: 0;
  padding: 0;
}

/* usually necessary for responsive layouts */
img, svg, textarea {
  max-width: 100%;
}

/* prevent viewbox from cropping out parts of the SVG */
svg {
  overflow: visible;
}

/* border box default: http:/*www.paulirish.com/2012/box-sizing-border-box-ftw/ */
html {
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}

/* position:relative by default, enables the following:
   - top/right/bottom/left adjustments,
   - z-index adjustements,
   - contained position:absolute behavior for children */
body * {
  position: relative;
}

/* prevent horizontal overflow and scroll bars on the page */
html, body {
  overflow-x: hidden;
  width: 100%;
}

/* nice defaults for form fields */
label {
  display: inline-block;
}
input, textarea {
  display: block;
  width: 100%;
}
input[type=checkbox],
input[type=radio]{
  vertical-align: baseline;
}
input[type=submit],
input[type=radio],
input[type=checkbox],
button,
label {
  cursor: pointer;
}

/* allow users resize textareas vertically (set max-height if necessary) */
textarea {
  resize: vertical;
}

/* reset button appearance */
button {
  overflow: visible;
  cursor: pointer;
  background: transparent;
  border: none;
  -webkit-appearance: button;
  display: block;
  outline: none;
  box-shadow: none;

  &::-moz-focus-inner {
    border: 0
  }
}

/* reset lists */
ul, ol {
  list-style: none;
}

/* add IE support for hidden attribute */
[hidden] {
  display: none;
}

/* reset cursor on disabled elements */
[disabled] {
  cursor: default;
}

/* -----------------------------
cherry picked from normalize
----------------------------- */

/* prevent iOS text size adjust after orientation change,
   without disabling user zoom. */
html {
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}

/* display: block defaults (img added by me ) */
article, aside, details, figcaption, figure, img,
footer, header, hgroup, main, menu, nav, section, summary {
  display: block;
}

/* sub / superscript sizing & positioning */
sub,
sup {
  font-size: 75%;
  line-height: 0;
  vertical-align: baseline;
}
sup {
  top: -0.5em;
}
sub {
  bottom: -0.25em;
}

/* remove image border */
img {
  border: 0;
}

/* have fields inherit font and color by default */
button, input, optgroup, select, textarea {
  color: inherit;
  font: inherit;
}

/* IE overflow bug */
button {
  overflow: visible;
}

/* address inconsistent text-transform inheritance */
button, select {
  text-transform: none;
}

/* Firefox fixes */
button::-moz-focus-inner,
input::-moz-focus-inner {
  border: 0;
}
input {
  line-height: normal;
}

/* Safari & Chrome fixes */
input[type="search"] {
  -webkit-appearance: textfield;
}
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}

/* reset fieldset border */
fieldset {
  border: none;
}

/* IE scrollbar */
textarea {
  overflow: auto;
}

/* table defaults */
table {
  border-collapse: collapse;
  border-spacing: 0;
}
```
